### ISSUE TITLE
Ski lift not shown

### ISSUE THREAD

**Issue by mdehollander** [mapbox/mapbox-studio-outdoors.tm2#6]
Hi, 

I started exploring mapbox studio for styling and I like it. However, I noticed a difference between openstreetmap and the Mapbox Outdoors style. 
When I look at a region of interest in openstreetmap I see 3 ski lifts: http://www.openstreetmap.org/search?query=sureanu#map=13/45.5631/23.5119
However when I look at the same region using the Mapbox Outdoor style there is none: http://a.tiles.mapbox.com/v3/aj.um7z9lus/page.html#13/45.5631/23.5119

Or when browsing with https://www.mapbox.com/editor/ I see one Lift present, and in the Run/Bike/Hike style it is not there.

Is it possible to show all 3 lifts using Mapbox Outdoors? Any idea why they are not shown all? Is it possible to adjust the aerialway=platter style? But this does not explain why there is only shown one.

**Comment by ajashton** [comment]
Hi,

The `mapbox.mapbox-streets-v6` vector tiles currently only contain aerialways of the following types: 'cable_car', 'chair_lift', 'drag_lift', 'gondola', 'mixed_lift'. I don't think there's any reason why platter, t-bar, and other popular types are excluded - it was probably an oversight. We are working on an update that will include all aerialway types.

`aj.um7z9lus` is an old prototype style not intended for general use, which is why it looks different than the one on <https://www.mapbox.com/editor>. The up-do-date version of the style has the ID `mapbox.outdoors`.

For now you will only be able to see the chair lift that is there unless you add a custom data layer to include the other types. Here's a guide about how to do that: https://www.mapbox.com/help/overpass-turbo/
